console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  black = '#141b1e'
  darkgray = '#232a2d'
  red = '#e57474'
  green = '#8ccf7e'
  yellow = '#e5c76b'
  blue = '#67b0e8'
  magenta = '#c47fd5'
  cyan = '#6cbfbf'
  lightgray = '#b3b9b8'
  white = '#dadada'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  ## Path desc
  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:cyan'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  ## Git status
  [[blocks.segments]]
  type = "git"
  style = "plain"
  foreground = "p:green"
  foreground_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}",
    "{{ if gt .Ahead 0 }}p:magenta{{ end }}",
    "{{ if gt .Behind 0 }}p:magenta{{ end }}"
  ]

  # Comprehensive template with clear distinction between unstaged and staged files
  template = """ {{ .HEAD }}{{ if .Working.Untracked }} ?{{ .Working.Untracked }}{{ end }}{{ if .Staging.Added }} +{{ .Staging.Added }}{{ end }}{{ if .Working.Modified }} *{{ .Working.Modified }}{{ end }}{{ if .Staging.Modified }} ~{{ .Staging.Modified }}{{ end }}{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}"""

  [blocks.segments.properties]
  fetch_status = true
  branch_icon = ''
  commit_icon = '@'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    background = 'transparent'
    # foreground = 'p:white'
    template = '<yellow>{{ .FormattedMs }}</>'

      [blocks.segments.properties]
        style = 'round'

## blank line
[[blocks]]
    type = 'prompt'
    alignment = 'left'
    newline = true

  ## Prompt arrow + Where we write cmds
  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    background = 'transparent'
    foreground_templates = [
      '{{if gt .Code 0}}p:red{{ else }}p:green{{ end }}'

    ]
    # template = '{{ if eq .Shell "zsh"}} {{else}}{{.Shell}} {{end}}'
    template ='{{ if .Env.VIRTUAL_ENV }}{{ .Env.VIRTUAL_ENV | base }}❯{{else}}❯{{ end }}'

[transient_prompt]
  background = 'transparent'
    foreground_templates = [
      '{{if gt .Code 0}}p:red{{ else }}p:green{{ end }}'

    ]
  template = '❯ '

# [secondary_prompt]
#   template = '<p:yellow,transparent></><,p:yellow> > </><p:yellow,transparent></> '
#   foreground = 'p:black'
#   background = 'transparent'
#
# [transient_prompt]
#   template = '<p:yellow,transparent></><,p:yellow> {{ .Folder }} </><p:yellow,transparent></> '
#   foreground = 'p:black'
#   background = 'transparent'
#
# [upgrade]
#   source = 'cdn'
#   interval = '168h'
#   auto = false
#   notice = false
#
# [[tooltips]]
#   leading_diamond = ''
#   trailing_diamond = ''
#   template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
#   foreground = 'p:white'
#   background = 'p:orange'
#   type = 'aws'
#   style = 'diamond'
#   tips = ['aws']
#
#   [tooltips.properties]
#     display_default = true
#
# [[tooltips]]
#   leading_diamond = ''
#   trailing_diamond = ''
#   template = '  {{ .Name }} '
#   foreground = 'p:white'
#   background = 'p:blue'
#   type = 'az'
#   style = 'diamond'
#   tips = ['az']
#
#   [tooltips.properties]
#     display_default = true
#
# [[blocks]]
#   type = 'prompt'
#   alignment = 'left'
#
#   [[blocks.segments]]
#     leading_diamond = ''
#     trailing_diamond = ''
#     template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }} '
#     foreground = 'p:black'
#     background = 'p:yellow'
#     type = 'session'
#     style = 'diamond'
#
#   [[blocks.segments]]
#     template = '  {{ path .Path .Location }} '
#     foreground = 'p:white'
#     powerline_symbol = ''
#     background = 'p:orange'
#     type = 'path'
#     style = 'powerline'
#
#     [blocks.segments.properties]
#       style = 'folder'
#
#   [[blocks.segments]]
#     template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
#     foreground = 'p:black'
#     powerline_symbol = ''
#     background = 'p:green'
#     type = 'git'
#     style = 'powerline'
#     foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}', '{{ if gt .Ahead 0 }}p:white{{ end }}']
    # background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}#49416D{{ end }}', '{{ if gt .Behind 0 }}#7A306C{{ end }}']
#
#     [blocks.segments.properties]
#       branch_template = '{{ trunc 25 .Branch }}'
#       fetch_status = true
#       fetch_upstream_icon = true
#
#   [[blocks.segments]]
#     template = '  '
#     foreground = 'p:white'
#     powerline_symbol = ''
#     background = 'p:yellow'
#     type = 'root'
#     style = 'powerline'
#
#   [[blocks.segments]]
#     leading_diamond = '<transparent,background></>'
#     trailing_diamond = ''
#     template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
#     foreground = 'p:white'
#     background = 'p:blue'
#     type = 'status'
#     style = 'diamond'
#     background_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
#
#     [blocks.segments.properties]
#       always_enabled = true
#
# [[blocks]]
#   type = 'rprompt'
#
#   [[blocks.segments]]
#     template = ' '
#     foreground = 'p:green'
#     background = 'transparent'
#     type = 'node'
#     style = 'plain'
#
#     [blocks.segments.properties]
#       display_mode = 'files'
#       fetch_package_manager = false
#       home_enabled = false
#
#   [[blocks.segments]]
#     template = ' '
#     foreground = 'p:blue'
#     background = 'transparent'
#     type = 'go'
#     style = 'plain'
#
#     [blocks.segments.properties]
#       fetch_version = false
#
#   [[blocks.segments]]
#     template = ' '
#     foreground = 'p:yellow'
#     background = 'transparent'
#     type = 'python'
#     style = 'plain'
#
#     [blocks.segments.properties]
#       display_mode = 'files'
#       fetch_version = false
#       fetch_virtual_env = false
#
#   [[blocks.segments]]
#     template = 'in <p:blue><b>{{ .Name }}</b></> '
#     foreground = 'p:white'
#     background = 'transparent'
#     type = 'shell'
#     style = 'plain'
#
#   [[blocks.segments]]
#     template = 'at <p:blue><b>{{ .CurrentDate | date "15:04:05" }}</b></>'
#     foreground = 'p:white'
#     background = 'transparent'
#     type = 'time'
#     style = 'plain'
